# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
# require 'resque/tasks'
# require 'resque/scheduler/tasks'
require './app/jobs/mailer.rb'
# namespace :resque do
# 	task :setup do
# 		require "resque"
# 		require "resque-scheduler"

# 		Resque.schedule = YAML.load_file('./scheduler.yml')
# 	end

# 	task :setup_schedule => :setup do
#     require 'resque-scheduler'

#   end
# 	task scheduler: :setup_schedule
# end
require 'resque/tasks'


task "resque:setup" => :environment
# namespace :resque do
#   task :setup do
#     require 'resque'
#     require 'resque-scheduler'
#   end
# end